config/routes.rb
Rails.application.routes.draw do
  root to: "application#home"

  #users
  devise_for :users
  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end
  get "/profile" => "profile#show", as: :profile_show
  get "/profile/edit" => "profile#edit", as: :profile_edit
  patch "profile/update" => "profile#update"
  get "/payments/all" => "payments#index", as: :payments_all_path
  get "/payments/fact" => "payments#edit_fact", as: :payments_fact
  get "/payments/delivery" => "payments#edit_delivery", as: :payments_delivery
  get "/payments/show" => "payments#show", as: :payments_show
  get "/payments/buy" => "payments#new_charge", as: :payments_buy
  get "/payments/destroy" => "payments#destroy", as: :payments_destroy
  get "/payments/success" => "payments#success", as: :payments_success
  post "/payments/charge" => "payments#buy", as: :payments_charge

  get "/shopping/all" => "shopping_cart#all", as: :shopping_all


  resources :payments
  resources :products
  resources :categories


  #shopping_cart
  get 'cart' => "shopping_cart#index", as: :cart
  get 'cart/add/:id' => 'shopping_cart#add', as: :product_to_cart
  get 'cart/clear' => "shopping_cart#clear", as: :cart_clear
  get "cart/remove/:id" => "shopping_cart#remove", as: :remove_product_from_cart
  get "cart/remove/:id/:quantity" => "shopping_cart#remove", as: :remove_products_from_cart


end

app/models/shopping_cart.rb
# == Schema Information
#
# Table name: shopping_carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ShoppingCart < ApplicationRecord
  acts_as_shopping_cart
  def tax_pct
    0
  end
  belongs_to :payments
end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
  end

  def clear
    @shopping_cart.clear
    render "shopping_cart/index"
  end

  def validate_facturation
  end

  def all
    @shopping_carts = ShoppingCart.all
  end

  def validate_delivery
  end

  def validate_recap
  end

  def validate_payment
  end

  def add
    product = Product.find(params[:id])
    quantity = 1
    if params.include? :quantity
      quantity = params[:quantity].to_i.abs
    end

    @shopping_cart.add(product, product.price, quantity)

    if request.xhr?
      render :json => {
        :total => @shopping_cart.total,
        :items => @shopping_cart.shopping_cart_items.length
        }
    else
      redirect_to cart_path
    end

  end

  def remove
    product = Product.find(params[:id])
    quantity = 1

    if params.include? :quantity
      quantity = params[:quantity].to_i.abs
    end

    @shopping_cart.remove(product, quantity)

    redirect_to cart_path
  end
end

app/views/shopping_cart/all.html.erb
<div class="container">
  <% @shopping_carts.each do |s| %>
    <%= debug s %>
  <% end %>
</div>

app/views/shopping_cart/index.html.erb
<div class="container" id="shopping_cart">
  <% if @shopping_cart.shopping_cart_items.length > 0 %>
  <%= link_to "Vider mon panier", cart_clear_path, class:"btn" %>
  <h2>Panier</h2>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Quantité</th>
        <th>Prix</th>
      </tr>
    </thead>
    <tbody>
    <% @shopping_cart.shopping_cart_items.each do |cart_item| %>
      <tr class="product-row">
        <td class="product">
          <%= image_tag cart_item.item.images[0].file.url(:thumb) %>
          <div class="content">
            <p class="title"><%= cart_item.item.name %></p>
            <p class="description"><%= cart_item.item.description %></p>
            <%= link_to "Supprimer", remove_products_from_cart_path({ id: cart_item.item.id, quantity: cart_item.quantity }), class: "delete" %>
          </div>
        </td>
        <td class="quantity">
          <%= link_to "-", remove_product_from_cart_path(cart_item.item.id), class: "btn-small" %><%= cart_item.quantity %><%= link_to "+", product_to_cart_path(cart_item.item.id), class: "btn-small" %>
        </td>
        <td class="price">
          <%= cart_item.price*cart_item.quantity %>
        </td>
      </tr>
    <% end %>
    <tbody>
  <table>
  <%= link_to "Commander", payments_fact_path, class: "btn btn-command" %>
  <% else  %>
  <p>Votre panier est vide</p>
  <% end %>
</div>