config/routes.rb
Rails.application.routes.draw do
  root to: "application#home"

  #users
  devise_for :users
  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end
  get "/profile" => "profile#show", as: :profile_show
  get "/profile/edit" => "profile#edit", as: :profile_edit
  patch "profile/update" => "profile#update"
  get "/payments/all" => "payments#index", as: :payments_all_path
  get "/payments/fact" => "payments#edit_fact", as: :payments_fact
  get "/payments/delivery" => "payments#edit_delivery", as: :payments_delivery
  get "/payments/show" => "payments#show", as: :payments_show
  get "/payments/buy" => "payments#new_charge", as: :payments_buy
  get "/payments/destroy" => "payments#destroy", as: :payments_destroy
  get "/payments/success" => "payments#success", as: :payments_success
  post "/payments/charge" => "payments#buy", as: :payments_charge

  get "/shopping/all" => "shopping_cart#all", as: :shopping_all


  resources :payments
  resources :products
  resources :categories


  #shopping_cart
  get 'cart' => "shopping_cart#index", as: :cart
  get 'cart/add/:id' => 'shopping_cart#add', as: :product_to_cart
  get 'cart/clear' => "shopping_cart#clear", as: :cart_clear
  get "cart/remove/:id" => "shopping_cart#remove", as: :remove_product_from_cart
  get "cart/remove/:id/:quantity" => "shopping_cart#remove", as: :remove_products_from_cart


end

app/models/payment.rb
class Payment < ApplicationRecord
  has_one :shopping_cart
  belongs_to :user
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :extract_payment, except: :index
  before_action :define_next_route, only: :update
  before_action :hydrate_present_attributes, only: [:edit_fact, :edit_delivery]
  before_action :test_admin, only: :index

  # GET /payments/all
  # Liste de toute les commande (debuggage)
  def index
    @payments = Payment.all
  end

  # GET /payments/fact
  #Formulaire de la facturation
  def edit_fact
    if @shopping_cart.shopping_cart_items.length < 1
      redirect_to root_path
    end
  end

  # GET /payments/delivery
  #Formulaire de la livraison
  def edit_delivery
    if !test_present_attributes([:fact_firstname, :fact_lastname, :fact_address, :fact_zipcode, :fact_city])
      redirect_to payments_fact_path
    end
  end

  # GET /payments/show
  #Récapitulatif du paiement
  def show
    if !test_present_attributes([:deliver_firstname, :deliver_lastname, :deliver_address, :deliver_zipcode, :deliver_city])
      redirect_to payments_delivery_path
    end
  end

  # GET /payments/buy
  #Lancement de l'achat
  def new_charge
  end


  # GET /payments/success
  #Rendu du succès après achat
  def success
  end


  # POST /payments/charge
  #Lance l'action de l'achat
  def buy
    @amount = (@payment.shopping_cart.total*100).to_i

    customer = Stripe::Customer.create(
      :email => @payment.user.email,
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    @shopping_cart.save
    session[:shopping_cart_id] = nil
    session[:payment_id] = nil

    @payment.complete = true
    @payment.save

    redirect_to payments_success_path
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to payments_success_path
  end


  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: "Le payment a bien été crée." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @next_route, notice: "Le payment a bien été mis à jour."  }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Le payment a bien été détruit."  }
      format.json { head :no_content }
    end
  end

  private

    def test_admin
      if !current_user || !current_user.admin
        redirect_to root_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:fact_firstname, :fact_lastname, :fact_address, :fact_addresscomplement, :fact_addresscomplementbis, :fact_zipcode, :fact_city, :deliver_firstname, :deliver_lastname, :deliver_address, :deliver_addresscomplement, :deliver_addresscomplementbis, :deliver_zipcode, :deliver_city)
    end

    #Définis la route suivante après submit
    def define_next_route
      step = params[:payment][:step]
      if !step.empty?
        case step
        when "fact"
          @next_route = "/payments/delivery"
        when "delivery"
          @next_route = "/payments/show"
        when "recap"
          @next_route = "/payments/buy"
        end
      else
        @next_route = "/"
      end
    end

    #Récupère l'objet paiment et assigne les attributs nécéssaire :
    #user / shopping_cart / session[:payment_id]
    def extract_payment
      payment_id = session[:payment_id].to_i
      if Payment.exists?(payment_id)
        @payment = Payment.find(payment_id)
      else
        @payment = Payment.create
      end
      session[:payment_id] = @payment.id

      if current_user
        if current_user != @payment.user
          @payment.user = current_user
        end
      else
        @payment.user = User.where(email: "guest@guest.com").first
      end

      @payment.shopping_cart  = @shopping_cart
    end


    # test la présence des attribut listé dans l'objet paiment
    def test_present_attributes(attributes)
      testPresence = true
      attributes.each do |a|
        if !@payment.attribute_present?(a)
          return false
        end
      end
    end


    #Hydrate les attributs par défault en fonction des données préenregistrer
    def hydrate_present_attributes
      fact_attributes = [:fact_firstname, :fact_lastname, :fact_address, :fact_zipcode, :fact_city]
      deliver_attributes = [:deliver_firstname, :deliver_lastname, :deliver_address, :deliver_zipcode, :deliver_city]
      user_attributes = [:firstname, :lastname, :address, :zipcode, :city]
      i=0
      while i<user_attributes.length do
        if !@payment[fact_attributes[i]] && @payment.user[user_attributes[i]]
          @payment[fact_attributes[i]] = @payment.user[user_attributes[i]]
        end
        if !@payment[deliver_attributes[i]] && @payment[fact_attributes[i]]
          @payment[deliver_attributes[i]] = @payment[fact_attributes[i]]
        end
        i += 1
      end
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_arianne.html.erb
<div class="arianne-container">
  <ul>
    <%= link_to payments_fact_path do %>
      <li class="arianne-item <% if current_page?(payments_fact_path) %>active<% end %>">Facturation</li>
    <% end %>
    <%= link_to payments_delivery_path do %>
      <li class="arianne-item <% if current_page?(payments_delivery_path) %>active<% end %>">Livraison</li>
    <% end %>
    <%= link_to payments_show_path do %>
      <li class="arianne-item <% if current_page?(payments_show_path) %>active<% end %>">Recapitulatif</li>
    <% end %>
    <%= link_to payments_buy_path do %>
      <li class="arianne-item <% if current_page?(payments_buy_path) %>active<% end %>">Paiement</li>
    <% end %>
  </ul>
</div>

app/views/payments/edit_delivery.html.erb
<div class="container" id="payments_container">
  <%= render "arianne" %>
  <%= form_for @payment do |f| %>
    <h2>Livraison</h2>
    <div class="form-group">
      <%= f.label :deliver_firstname, "Prénom *" %>
      <%= f.text_field :deliver_firstname, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :deliver_lastname, "Nom *" %>
      <%= f.text_field :deliver_lastname, class:"form-control" %>
    </div>
    <div class="form-group form-large">
      <%= f.label :deliver_address, "Adresse de livraison *" %>
      <%= f.text_field :deliver_address, class:"form-control" %>
    </div>
    <div class="form-group form-large">
      <%= f.label :deliver_addresscomplement, "Complément d'addresse" %>
      <%= f.text_field :deliver_addresscomplement, class:"form-control" %>
    </div>
    <div class="form-group form-large">
      <%= f.label :deliver_addresscomplementbis, "Complément d'addresse bis" %>
      <%= f.text_field :deliver_addresscomplementbis, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :deliver_zipcode, "Code postal *" %>
      <%= f.text_field :deliver_zipcode, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :deliver_city, "Ville *" %>
      <%= f.text_field :deliver_city, class:"form-control" %>
    </div>
    <%= f.hidden_field :step, value: "delivery" %>
    <div class="actions">
      <%= f.submit class:"btn btn-primary btn-command", value:"Recapitulatif" %>
    </div>
  <% end %>
</div>

app/views/payments/edit_fact.html.erb
<div class="container" id="payments_container">
  <%= render "arianne" %>
  <%= form_for @payment do |f| %>
  <h2>Facturation</h2>
    <div class="form-group">
      <%= f.label :fact_firstname, "Prénom *" %>
      <%= f.text_field :fact_firstname, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :fact_lastname, "Nom *" %>
      <%= f.text_field :fact_lastname, class:"form-control" %>
    </div>
    <div class="form-group form-large">
      <%= f.label :fact_address, "Addresse de facturation *" %>
      <%= f.text_field :fact_address, class:"form-control" %>
    </div>
    <div class="form-group form-large">
      <%= f.label :fact_addresscomplement, "Complément d'adresse" %>
      <%= f.text_field :fact_addresscomplement, class:"form-control" %>
    </div>
    <div class="form-group form-large">
      <%= f.label :fact_addresscomplementbis, "Complement d'adresse bis" %>
      <%= f.text_field :fact_addresscomplementbis, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :fact_zipcode, "Code Postal *" %>
      <%= f.text_field :fact_zipcode, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :fact_city, "Ville *" %>
      <%= f.text_field :fact_city, class:"form-control" %>
    </div>
    <%= f.hidden_field :step, value: "fact" %>
    <div class="actions">
      <%= f.submit class:"btn btn-primary btn-command", value:"Passer à la livraison" %>
    </div>
  <% end %>
</div>

app/views/payments/index.html.erb
<div>
  <ul>
    <% @payments.each do |payment| %>
      <% if payment.fact_firstname %>
        <li>
          <p><%= payment.fact_firstname %> <%= payment.fact_lastname %></p>
          <p><%= payment.fact_address %> <%= payment.fact_zipcode %> <%= payment.fact_city %></p>
          <p><%= payment.shopping_cart.shopping_cart_items.length %> produit(s) achetés</p>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/payments/new_charge.html.erb
<div class="container" id="payments_container">
  <%= render "arianne" %>
  <%= form_tag payments_charge_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Montant total à payer: <%= @payment.shopping_cart.total %></span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount= <%= @payment.shopping_cart.total*100 %>
            data-locale="auto"></script>
  <% end %>

</div>

app/views/payments/show.html.erb
<div class="container" id="payments_container">
  <%= render "arianne" %>
  <div class="recap-container">
    <div class="half-container">
      <h2>Adresse de facturation</h2>
      <p><%= @payment.fact_firstname %> <%= @payment.fact_lastname %></p>
      <p><%= @payment.fact_address %> <%= @payment.fact_addresscomplement %> <%= @payment.fact_addresscomplementbis %></p>
      <p><%= @payment.fact_zipcode %> <%= @payment.fact_city %></p>
    </div>
    <div class="half-container">
      <h2>Adresse de livraison</h2>
      <p><%= @payment.deliver_firstname %> <%= @payment.deliver_lastname %></p>
      <p><%= @payment.deliver_address %> <%= @payment.deliver_addresscomplement %> <%= @payment.deliver_addresscomplementbis %></p>
      <p><%= @payment.deliver_zipcode %> <%= @payment.deliver_city %></p>
    </div>
    <div class="shopping_cart">
      <h2>Commande</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Quantité</th>
            <th>Prix</th>
          </tr>
        </thead>
        <tbody>
        <% @payment.shopping_cart.shopping_cart_items.each do |p| %>
        <% product = Product.find(p.item_id) %>
        <tr class="product-row">
          <td class="product">
            <%= image_tag p.item.images[0].file.url(:thumb) %>
            <div class="content">
              <p class="title"><%= p.item.name %></p>
              <p class="description"><%= p.item.description %></p>
              <%= link_to "Supprimer", remove_products_from_cart_path({ id: p.item.id, quantity: p.quantity }), class: "delete" %>
            </div>
          </td>
          <td class="quantity">
            <%= p.quantity %>
          </td>
          <td class="price">
            <%= p.price*p.quantity %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>

  <%= link_to 'Acheter', payments_buy_path, class:"btn btn-command" %>
</div>

app/views/payments/success.html.erb
<div class="container" id="payments_container">
  <p>Fécilitation pour votre achat !</p>
</div>