config/routes.rb
Rails.application.routes.draw do
  root to: "application#home"

  #users
  devise_for :users
  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end
  get "/profile" => "profile#show", as: :profile_show
  get "/profile/edit" => "profile#edit", as: :profile_edit
  patch "profile/update" => "profile#update"
  get "/payments/all" => "payments#index", as: :payments_all_path
  get "/payments/fact" => "payments#edit_fact", as: :payments_fact
  get "/payments/delivery" => "payments#edit_delivery", as: :payments_delivery
  get "/payments/show" => "payments#show", as: :payments_show
  get "/payments/buy" => "payments#new_charge", as: :payments_buy
  get "/payments/destroy" => "payments#destroy", as: :payments_destroy
  get "/payments/success" => "payments#success", as: :payments_success
  post "/payments/charge" => "payments#buy", as: :payments_charge

  get "/shopping/all" => "shopping_cart#all", as: :shopping_all


  resources :payments
  resources :products
  resources :categories


  #shopping_cart
  get 'cart' => "shopping_cart#index", as: :cart
  get 'cart/add/:id' => 'shopping_cart#add', as: :product_to_cart
  get 'cart/clear' => "shopping_cart#clear", as: :cart_clear
  get "cart/remove/:id" => "shopping_cart#remove", as: :remove_product_from_cart
  get "cart/remove/:id/:quantity" => "shopping_cart#remove", as: :remove_products_from_cart


end

app/views/layouts/_popincart.html.erb
<div id="popinCart" class="hidden">
  <div class="container-popin">
    <div class="header-popin">
      <p class="title">Produit ajouté au panier avec succès !</p>
      <a href="" class="continue-cart">Continuer mes achats</a>
      <button id="close-popin"></button>
    </div>
    <div class="header-content">
      <div class="focus-product">
        <img src="" alt="" id="product-popin-img">
        <p id="product-popin-title">Chaussette édition spécial bird</p>
      </div>
      <div class="focus-cart">
        <p class="cart-amount">Votre panier :
          <span id="amount-popin-cart">1 article</span>
        </p>
        <p class="total">Total :
          <span id="total-popin-cart">14 euros</span>
        </p>
        <%= link_to "Commander maintenant", payments_fact_path, class:"btn btn-primary btn-command" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sock-It</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="nav-bar-left searchBar little">
        <form action="">
          <label class="magnifying_glass" for="search_bar"></label>
          <input id="search_bar" type="text" placeholder="Rechercher">
        </form>
      </div>
      <%= link_to root_path do %>
      <div class="nav-bar-center title-container">
        <%= link_to root_path do %>
        <h1>Sock-it</h1>
        <p class="sub-title">Paris</p>
        <% end %>
      </div>
      <% end %>

      <p id="burger-button">Menu</p>
      <div id="nav-burger-button" class="nav-bar-right nav-hidden">

        <% if user_signed_in? %>

          <div id="account_nav" class="small">
            <h3 id="button-account" class="button-header">Mon Compte</h3>
            <div class="nav">

              <% if current_user.admin===true %>
                <%= link_to products_path do %>
                  <p class="nav_log">
                    Admin
                  </p>
                <% end %>
              <% end %>
              <%= link_to edit_user_registration_path(current_user) do %>
                <p class="nav_log">
                  Editer connexion
                </p>
              <% end %>
              <%= link_to profile_edit_path(current_user) do %>
                <p class="nav_log">
                  Editer profile
                </p>
              <% end %>
              <%= link_to destroy_user_session_path, :method => :delete do %>
                <p class="nav_log">
                  Déconnexion
                </p>
              <% end %>

            </div>
          </div>
        <% else %>

          <%= link_to new_user_session_path do %>
            <div class="nav_log">
              <h3 class="button-header">Connexion</h3>
            </div>
          <% end %>

          <%= link_to new_user_registration_path do %>
            <div class="nav_log">
              <h3 class="button-header bg-button">Inscription</h3>
            </div>
          <% end %>

        <% end %>

        <%= link_to(cart_path) do %>
          <div class="cart">
            <span class="cart_icon"></span>
            <span class="number_article"><span id="header-total-count"><%= @shopping_cart.total %></span> €</span>
          </div>
        <% end %>

      </div>

    </header>
      <nav class="main-nav">
        <ul>
          <% @categories.each do |category| %>
            <%= link_to category_path(category) do %>
              <li><%= category.libCategory.upcase %></li>
            <% end %>
          <% end %>
          <a href="">
            <li>Nouveautés</li>
          </a>
          <a href="">
            <li>A Propos</li>
          </a>
        </ul>
      </nav>
      <% if notice %>
        <p id="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p id="alert"><%= alert %></p>
      <% end %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <script>
      var config = {
        "root" : "<%= root_url %>"
      }
    </script>
  </body>
</html>

app/views/layouts/home.html.erb
<div id="homepage" class="container">
  <div class="banner">
    <%= image_tag "banner.png" %>
  </div>
  <!-- <div class="wrapper-small"> -->
    <div class="products-container">
      <% i = 0 %>
      <% @products.each do |product| %>
      <div class="product">
        <p class="price"><%= product.price %>€</p>
        <div class="visuel">
          <%= image_tag product.images[0].file.url(:medium) %>
        </div>
        <div class="content">
          <%= link_to product do %>
          <p class="title"><%= product.name %></p>
          <% end %>
          <%= link_to "", product_to_cart_path(product.id), class: "add-product-to-cart", :data => {:url => product.images[0].file.url(:medium), :title =>  product.name }  %>
        </div>
      </div>
      <% i+=1 %>
      <% end %>
    </div>
    <%= render "layouts/popincart" %>